[build]
  command = ""
  publish = "."
  functions = "functions"

[dev]
  framework = "#custom"
  targetPort = 5500
  port = 8888
  autoLaunch = false

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
